[project]
name = "shrinkwrap"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.129.0",
    "gunicorn>=25.1.0",
    "uvicorn>=0.40.0",
]
